### ISSUE TITLE
Can't exit/get rid of listening status

### ISSUE THREAD

**Issue by techtonik** [nitroshare/nitroshare-android#26]
There are two issues:
1. I'd like to exit NitroShare to make it stop scanning local network
2. I'd like to squelch NitroShare listening status - currently it is not possible to swipe it off like other status messages

**Comment by nathan-osman** [comment]
> I'd like to exit NitroShare to make it stop scanning local network

There is a setting that disables receiving transfers. You will have to enable it again when you are ready to receive a transfer.

> I'd like to squelch NitroShare listening status - currently it is not possible to swipe it off like other status messages

This is unfortunately impossible to fix thanks to the way Android deals with services. In order to remain running in the background, a service must display a persistent notification. Originally it was even worse and a status icon was displayed but I figured out how to hide it.

**Comment by techtonik** [comment]
Is it possible to just add `Exit` item to application menu?

**Comment by nathan-osman** [comment]
This is possible. I can add an exit item to the sliding menu.
