### ISSUE TITLE
Where to find the APK?

### ISSUE THREAD

**Issue by IzzySoft** [nitroshare/nitroshare-android#44]
The app description (and its screenshots) look promising – but I found no hint on where to get the `.apk`. Would you mind attaching it to the corresponding `releases/`? Or would you mind having it included with F-Droid?

**Comment by nathan-osman** [comment]
Good idea. I'll make a habit of adding the release APK to each tag, starting with this one: https://github.com/nitroshare/nitroshare-android/releases/tag/0.4.0.36

**Comment by IzzySoft** [comment]
Cool! That was fast! I hope you don't mind a [little promotion](https://apt.izzysoft.de/fdroid/index/apk/net.nitroshare.android)? Also, as initially pointed out, if you wish I could rrequest to have your app included with the official F-Droid repository. As far as I can see, it should meet the "inclusion criteria" (not being a dev, I might have missed something though ;)

**Comment by nathan-osman** [comment]
Sure, I'd love to have it included in F-Droid.

**Comment by IzzySoft** [comment]
OK then, I've [initiated that](https://gitlab.com/fdroid/rfp/issues/481). Feel free to "chime in" – and it might be a good idea to keep an eye on it, in case the maintainers need some input :wink:

**Comment by relan** [comment]
@nathan-osman, I'm F-Droid maintaner and I'd like to add Nitroshare into F-Droid main repo. Unfortunately 0.4.0.37 does not build:

> Could not find com.android.tools.build:gradle:3.0.0

This happens because top-level build.gradle is missing Google Maven repository: https://github.com/nitroshare/nitroshare-android/blob/0.4.0.37/build.gradle#L4 Android Studio adds it implicitly, but F-Droid uses command line tools to build apps.

More about top-level build.gradle: https://developer.android.com/studio/build/index.html#top-level

Steps to reproduce:

    cd app
    gradle assembleRelease

**Comment by nathan-osman** [comment]
@relan Thanks! I've pushed a fix for that and bumped the version to 0.4.0.38.

**Comment by relan** [comment]
Added in [this commit](https://gitlab.com/fdroid/fdroiddata/commit/e7be24257211861499123498540ba54cf52b5c14). Thanks!
