### ISSUE TITLE
Cannot use on Android 9 or 10

### ISSUE THREAD

**Issue by puppykickr** [nitroshare/nitroshare-android#96]
I have been using this app ever since 5.1.1 with great results.

It seems to not be able to find devices that are Android 9 or above.

**Comment by Build-0-Matic** [comment]
I found that if I force stop the Android version and restart it, I can see it. But after that you get a connection failed error (timeout) on the sending computer.
It's like if the Android version needed an incoming network connection but 'Droid refused to open it.
Really annoying because it works fine from Android to Computer, just not the other way around.

**Comment by puppykickr** [comment]
I found what appears to be a workaround.
As I was looking at various other apps to do the same thing, I got frustrated (because all the rest are crap) and tried NitroShare again.

As I was frusrtrated, I had forgotten and left the last app I had tried running, Warpinator.
Imagine my surprise when NitroShare suddenly worked perfectly!

I later tried again, this time with Warpinator off, and NitroShare would not work.

Turned Warpinator back on, and NitroShare worked again.

Try it and see if it works for you as well.

**Comment by Build-0-Matic** [comment]
I'll have to try this.
Still, it's not what I would call normal behavior for an app to require another one in order to work.

In the end, in order to transfer files I opted to just use the CX File Explorer on the Android device and FTP into it using Filezilla.
Not the most fun way to do it but it gets the job done.

**Comment by puppykickr** [comment]
I don't know why, but the issue seems to have resolved itself.

I have been transfering files back and forth without issue, and without using additional apps.

So I will be closing this issue.
